### ISSUE TITLE
Possibility of using this project to configure an USB-midi host instead of a device.

### ISSUE THREAD

**Issue by DianaSotelo9914** [altineller/usb_dev_midi#1]
Hi, I was wondering if it was possible to use this code as a base to use the TM4C123GH6PM as an USB-midi host instead of an USB-midi device and where should I start. Do you know if it would be possible?

**Comment by altineller** [comment]
Hello, I think the answer is no. This code is focused on the USB device emulating devices or clients, on a specific platform. However, maybe midi-host device can be encapsulated over virtual serial offered by the tivaC's usbcdc.

**Comment by bouge13a** [comment]
I think it is possible, however, the tm4c is not designed or equipped to be a synthesizer.

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 27, 2024 at 1:50 PM, Can ***@***.***> wrote:   


Hello, I think the answer is no. This code is focused on the USB device emulating devices or clients, on a specific platform. However, maybe midi-host device can be encapsulated over virtual serial offered by the tivaC's usbcdc.

**Comment by aspdigital** [comment]
> Hi, I was wondering if it was possible to use this code as a base to use the TM4C123GH6PM as an USB-midi host instead of an USB-midi device and where should I start. Do you know if it would be possible?

The USB-MIDI implementation here was designed as a _device_. A host application is much more complicated and in any event wasn't the point of the original design task.

Are you clear on the differences between a USB Device and a USB Host?

**Comment by bouge13a** [comment]
Just use a teensy instead. It can act as a host  no need for a tm4c.

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 29, 2024 at 11:30 PM, Andy ***@***.***> wrote:   



Hi, I was wondering if it was possible to use this code as a base to use the TM4C123GH6PM as an USB-midi host instead of an USB-midi device and where should I start. Do you know if it would be possible?


The USB-MIDI implementation here was designed as a device. A host application is much more complicated and in any event wasn't the point of the original design task.

Are you clear on the differences between a USB Device and a USB Host?

**Comment by DianaSotelo9914** [comment]
Hi, thank you for your replies. My current target is to try and use the TM4C12X (I don't mind using the 123X or the 129X) to act as an interface between a MIDI-over-USB device (such as a keyboard) and typical MIDI cable (for example, to connect it to a synth). I fear I don't have much knowledge of USB protocols since this is for an education project so my original question was about the process of setting up an USB host using the USB MIDI class implemented on this project. 

I see now that this isn't an easy task and might be beyond the scope of this project, so I might consider using a Teensy since apparently TM4C libraries on USB seem to be exceptionally confusing. Thank you again for the help and answers!
